manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 308d6bce6eb338f387a454c7366d0bcb07463d7b
      import: app/west.yml
  self:
    path: config
